# Health check configuration for all services
apiVersion: v1
kind: ConfigMap
metadata:
  name: health-check-config
  namespace: fullstack-monolith
data:
  health-check.sh: |
    #!/bin/bash

    # Health check script for comprehensive service monitoring

    # Colors for output
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    NC='\033[0m' # No Color

    # Configuration
    API_URL="${API_URL:-http://api-service:3000}"
    WEB_URL="${WEB_URL:-http://web-service:3001}"
    DB_HOST="${DB_HOST:-postgres-service}"
    DB_PORT="${DB_PORT:-5432}"
    REDIS_HOST="${REDIS_HOST:-redis-service}"
    REDIS_PORT="${REDIS_PORT:-6379}"

    # Function to check HTTP endpoint
    check_http() {
        local url=$1
        local name=$2
        local timeout=${3:-10}
        
        echo -n "Checking $name... "
        
        if curl -f -s --max-time $timeout "$url/health" > /dev/null 2>&1; then
            echo -e "${GREEN}✓ Healthy${NC}"
            return 0
        else
            echo -e "${RED}✗ Unhealthy${NC}"
            return 1
        fi
    }

    # Function to check TCP port
    check_tcp() {
        local host=$1
        local port=$2
        local name=$3
        local timeout=${4:-5}
        
        echo -n "Checking $name... "
        
        if timeout $timeout bash -c "cat < /dev/null > /dev/tcp/$host/$port" 2>/dev/null; then
            echo -e "${GREEN}✓ Reachable${NC}"
            return 0
        else
            echo -e "${RED}✗ Unreachable${NC}"
            return 1
        fi
    }

    # Function to check database
    check_database() {
        echo -n "Checking PostgreSQL... "
        
        if pg_isready -h $DB_HOST -p $DB_PORT -q; then
            echo -e "${GREEN}✓ Ready${NC}"
            return 0
        else
            echo -e "${RED}✗ Not Ready${NC}"
            return 1
        fi
    }

    # Function to check Redis
    check_redis() {
        echo -n "Checking Redis... "
        
        if redis-cli -h $REDIS_HOST -p $REDIS_PORT ping | grep -q PONG; then
            echo -e "${GREEN}✓ Responding${NC}"
            return 0
        else
            echo -e "${RED}✗ Not Responding${NC}"
            return 1
        fi
    }

    # Main health check
    main() {
        echo "=== Fullstack Monolith Health Check ==="
        echo "Timestamp: $(date)"
        echo
        
        local exit_code=0
        
        # Check core services
        check_http "$API_URL" "API Service" || exit_code=1
        check_http "$WEB_URL" "Web Service" || exit_code=1
        
        # Check databases
        check_database || exit_code=1
        check_redis || exit_code=1
        
        # Check infrastructure
        check_tcp "$DB_HOST" "$DB_PORT" "PostgreSQL Port" || exit_code=1
        check_tcp "$REDIS_HOST" "$REDIS_PORT" "Redis Port" || exit_code=1
        
        echo
        if [ $exit_code -eq 0 ]; then
            echo -e "${GREEN}All services are healthy!${NC}"
        else
            echo -e "${RED}Some services are unhealthy!${NC}"
        fi
        
        exit $exit_code
    }

    main "$@"

  deep-health-check.sh: |
    #!/bin/bash

    # Deep health check with detailed diagnostics

    # Function to check API endpoints
    check_api_endpoints() {
        echo "=== API Endpoint Health ==="
        
        local endpoints=(
            "/health"
            "/health/ready"
            "/health/live"
            "/metrics"
            "/api/v1/auth/status"
        )
        
        for endpoint in "${endpoints[@]}"; do
            echo -n "  $endpoint: "
            if curl -f -s --max-time 5 "$API_URL$endpoint" > /dev/null; then
                echo -e "${GREEN}✓${NC}"
            else
                echo -e "${RED}✗${NC}"
            fi
        done
    }

    # Function to check database performance
    check_database_performance() {
        echo "=== Database Performance ==="
        
        # Check connection count
        local conn_count=$(psql -h $DB_HOST -p $DB_PORT -U postgres -t -c "SELECT count(*) FROM pg_stat_activity;" 2>/dev/null | xargs)
        echo "  Active connections: ${conn_count:-N/A}"
        
        # Check slow queries
        local slow_queries=$(psql -h $DB_HOST -p $DB_PORT -U postgres -t -c "SELECT count(*) FROM pg_stat_activity WHERE state = 'active' AND query_start < now() - interval '30 seconds';" 2>/dev/null | xargs)
        echo "  Slow queries (>30s): ${slow_queries:-N/A}"
        
        # Check database size
        local db_size=$(psql -h $DB_HOST -p $DB_PORT -U postgres -t -c "SELECT pg_size_pretty(pg_database_size('fullstack_production'));" 2>/dev/null | xargs)
        echo "  Database size: ${db_size:-N/A}"
    }

    # Function to check Redis performance
    check_redis_performance() {
        echo "=== Redis Performance ==="
        
        # Check memory usage
        local memory_used=$(redis-cli -h $REDIS_HOST -p $REDIS_PORT info memory | grep used_memory_human | cut -d: -f2 | tr -d '\r')
        echo "  Memory used: ${memory_used:-N/A}"
        
        # Check connected clients
        local clients=$(redis-cli -h $REDIS_HOST -p $REDIS_PORT info clients | grep connected_clients | cut -d: -f2 | tr -d '\r')
        echo "  Connected clients: ${clients:-N/A}"
        
        # Check keyspace
        local keys=$(redis-cli -h $REDIS_HOST -p $REDIS_PORT info keyspace | grep db0 | cut -d: -f2 | cut -d, -f1 | cut -d= -f2)
        echo "  Total keys: ${keys:-0}"
    }

    # Main function
    main() {
        echo "=== Deep Health Check ==="
        echo "Timestamp: $(date)"
        echo
        
        check_api_endpoints
        echo
        check_database_performance
        echo
        check_redis_performance
    }

    main "$@"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check-cron
  namespace: fullstack-monolith
spec:
  schedule: '*/5 * * * *' # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: health-checker
              image: postgres:15-alpine
              command:
                - /bin/sh
                - -c
                - |
                  apk add --no-cache curl redis
                  /scripts/health-check.sh
              env:
                - name: API_URL
                  value: 'http://api-service:3000'
                - name: WEB_URL
                  value: 'http://web-service:3001'
                - name: DB_HOST
                  value: 'postgres-service'
                - name: REDIS_HOST
                  value: 'redis-service'
              volumeMounts:
                - name: health-check-scripts
                  mountPath: /scripts
          volumes:
            - name: health-check-scripts
              configMap:
                name: health-check-config
                defaultMode: 0755
          restartPolicy: OnFailure
